// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:db7c6052-9d55-4eda-bbda-4a6369f2b193',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsmobilehotelsmarts-hosting-mobilehub-2113242020',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2pzmp61nfzfxj.cloudfront.net',
    'aws_mobile_analytics_app_id': '03f119b3f8794fd5802a28abc4ecbea0',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e548ed8f-246b-4af4-8c0d-f36eb9f72f63',
    'aws_project_name': 'aws-mobile-hotel-smart-service',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'awsmobilehotelsmarts-mobilehub-2113242020',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_Ci0JQKvNd',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5ssauibfchic844i0nv602132r',
}

export default awsmobile;
